channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7.3
  - snakemake=5.16.0
  - bowtie2=2.3.5.1
  - samtools=1.7
  - deeptools=3.4.3
  - FastQC=0.11.9
  - multiqc=1.8
  - matplotlib=3.1.0



